# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 19:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_myadmin_logged_in'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyAdmin',
        ),
    ]
