# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20161031_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LDAP', models.IntegerField(null=True)),
                ('password', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('course', models.ManyToManyField(to='backend.Course')),
            ],
        ),
    ]
