# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_feedback_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadline',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
