# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20161102_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
