# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_student_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='LDAP_id',
        ),
        migrations.AddField(
            model_name='student',
            name='LDAP',
            field=models.IntegerField(null=True),
        ),
    ]
