# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_auto_20161104_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingQuestionResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opinion', models.IntegerField(choices=[(1, 'Strongly Agree'), (2, 'Agree'), (3, 'Neutral'), (4, 'Disagree'), (5, 'Strongly Disagree')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectiveQuestionResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opinion', models.CharField(max_length=100)),
                ('subjectivequestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.SubjectiveQuestion')),
            ],
        ),
        migrations.AlterModelOptions(
            name='deadline',
            options={'ordering': ['-due_date']},
        ),
        migrations.RemoveField(
            model_name='ratingquestion',
            name='opinion',
        ),
        migrations.AddField(
            model_name='ratingquestionresponse',
            name='ratingquestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.RatingQuestion'),
        ),
    ]
