# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(to='backend.Course'),
        ),
    ]
