# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_deadline_myadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='myadmin',
            name='logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
