# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 20:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_myadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
