# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_student_logged_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='LDAP',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
