# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_auto_20161103_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.CharField(max_length=100)),
                ('opinion', models.IntegerField(choices=[(1, 'Strongly Agree'), (2, 'Agree'), (3, 'Neutral'), (4, 'Disagree'), (5, 'Strongly Disagree')], default=1)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Feedback')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectiveQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.CharField(max_length=100)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Feedback')),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='feedback',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
